org: HiromiShikata
projectUrl: https://github.com/users/HiromiShikata/projects/49
projectName: test-project
manager: HiromiShikata
allowIssueCacheMinutes: 0
credentials:
  ghToken: your_gh_token_here
  bot:
    github:
      token: your_gh_token_here
workingReport:
  repo: test-repository
  members:
    - HiromiShikata
  spreadsheetUrl: https://docs.google.com/spreadsheets/d/your-sheet-id
  reportIssueLabels:
    - report
awaitingWorkspaceStatus: 'Awaiting workspace'
preparationStatus: 'Preparation'
defaultAgentName: 'impl'
allowedIssueAuthors: 'HiromiShikata,other-author'
awaitingQualityCheckStatus: 'Awaiting quality check'
